import { StyleSheet } from "react-native";

export const ui = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FAFAFB",
    paddingTop: 26,
    paddingHorizontal: 18,
    paddingBottom: 96,
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  brand: { fontSize: 25, fontWeight: "800", letterSpacing: 0.2 },
  subBrand: { marginTop: 2, fontSize: 12, opacity: 0.6 },

  headerRight: { flexDirection: "row", alignItems: "center", gap: 10 },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#EEE",
  },
  iconButtonText: { fontSize: 16, opacity: 0.8 },

  avatar: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#111",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#FFF", fontWeight: "700", fontSize: 12 },

  heroCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#EEE",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  heroTitle: { fontSize: 18, fontWeight: "800" },
  heroBody: { marginTop: 6, fontSize: 13, opacity: 0.7, lineHeight: 18 },

  primaryButton: {
    marginTop: 14,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#111",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryPressed: { opacity: 0.88 },
  primaryButtonText: { color: "#FFF", fontWeight: "700", fontSize: 15 },

  sectionHeader: {
    marginTop: 18,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
  },
  sectionTitle: { fontSize: 14, fontWeight: "700" },
  sectionHint: { fontSize: 12, opacity: 0.55 },

  previewCard: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: "#EEE",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 1,
  },
  previewImage: {
    width: 86,
    height: 120,
    borderRadius: 14,
    backgroundColor: "#F2F2F2",
  },
  previewMeta: { flex: 1, justifyContent: "space-between", paddingVertical: 2 },
  previewTitle: { fontSize: 14, fontWeight: "800" },
  previewSubtitle: { fontSize: 12, opacity: 0.6, marginTop: 2 },

  previewActions: { flexDirection: "row", gap: 10, marginTop: 10 },
  secondaryButton: {
    height: 38,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: "#111",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: { color: "#FFF", fontWeight: "700", fontSize: 13 },

  ghostButton: {
    height: 38,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: "#F3F3F5",
    alignItems: "center",
    justifyContent: "center",
  },
  ghostButtonText: { fontWeight: "700", fontSize: 13, opacity: 0.8 },

  emptyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#EEE",
    alignItems: "center",
  },
  emptyIcon: { fontSize: 26, marginBottom: 8 },
  emptyTitle: { fontSize: 14, fontWeight: "800" },
  emptyBody: { marginTop: 4, fontSize: 12, opacity: 0.65, textAlign: "center" },

  nav: {
    position: "absolute",
    left: 18,
    right: 18,
    bottom: 22,
    height: 72,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EEE",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    zIndex: 1,
  },
  navItem: { alignItems: "center", gap: 6 },
  navIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: "#F3F3F5",
    alignItems: "center",
    justifyContent: "center",
  },
  navIconWrapActive: { backgroundColor: "#111" },
  navIcon: { fontSize: 16, opacity: 0.8 },
  navIconActive: { color: "#FFF", opacity: 1 },
  navLabel: { fontSize: 11, opacity: 0.6, fontWeight: "600" },
  navLabelActive: { opacity: 1 },

  pressed: { opacity: 0.85 },
  sheetBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.25)",
    zIndex: 20,
  },

  sheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 14,
    borderWidth: 1,
    borderColor: "#EEE",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -8 },
    elevation: 10,
    zIndex: 30,
  },

  sheetHandle: {
    alignSelf: "center",
    width: 44,
    height: 5,
    borderRadius: 99,
    backgroundColor: "#DDD",
    marginBottom: 12,
  },

});